data_path_test: "/local/storage/imagenet_fire_testset"
measurement_save_path_test: "/local/storage/DDfire_PR/measurement_y_testset/ImageNet" # TODO: CHANGE THIS TO DESIRED OUT PATH

batch_size: 1
image_size: 256
preprocess: False

image_type: "imagenet"
deg: "pr_osf"

#HIO parameters:
hio_result_save_path: "/local/storage/DDfire_PR/HIO_Results/ImageNet" # TODO: CHANGE THIS TO DESIRED OUT PATH
HIO_iter_final: 1000
total_num_hio_runs: 4
HIO_iter_trials: 50
number_of_trials: 50
beta_HIO: 0.9