deg: "blur_motion"

noisy:
  20:
    K: 8
    delta_1: 0.20

  100:
    K: 50
    delta_1: 0.5

  1000:
    K: 500
    delta_1: 0.1

noiseless:
  20:
    K: 10
    delta_1: 0.25

  100:
    K: 50
    delta_1: 0.25

  1000:
    K: 500
    delta_1: 0.1