data_path_test: "/local/storage/FFHQ/ffhq256_firetest" # for 1000 test images
measurement_save_path_test: "/local/storage/DDfire_PR/measurement_y_testset/FFHQ" # TODO: CHANGE THIS TO DESIRED OUT PATH

batch_size: 1
image_size: 256

image_type: "ffhq"
deg: "pr_osf"

#HIO parameters:
hio_result_save_path: "/local/storage/DDfire_PR/HIO_Results/FFHQ" # TODO: CHANGE THIS TO DESIRED OUT PATH
HIO_iter_final: 1000
total_num_hio_runs: 4
HIO_iter_trials: 50
number_of_trials: 50
beta_HIO: 0.9
